### ISSUE TITLE
Iterations don't converge

### ISSUE THREAD

**Issue by jonadem** [Flow-Based-Cartograms/go_cart#9]
First of all, I must admit that I don't have much knowledge in GIS.

But this software seems interesting and I wanted to give it a go but I can't get a result for the world map.
I used the world map provided there : https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip
I convert the shp file into a gen file with this script : https://github.com/mgastner/shp2gen
I get this : https://www.dropbox.com/s/ni1sjgq58lyr4di/world.gen?dl=0
I made a dat file (all weights are set to 1) : https://www.dropbox.com/s/35r5xhgrz6kk1gi/world_test.dat?dl=0
The cartogram script ran for a whole night and I stopped it while the output was like this:
```
...
Starting integration 45643
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.593742e-01, delta_t = 2.593742e-02
iter = 20, t = 5.727500e-01, delta_t = 6.727500e-02
max. abs. area error: 240.000000
Starting integration 45644
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.593742e-01, delta_t = 2.593742e-02
iter = 20, t = 5.727500e-01, delta_t = 6.727500e-02
max. abs. area error: 240.000000
Starting integration 45645
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.593742e-01, delta_t = 2.593742e-02
iter = 20, t = 5.727500e-01, delta_t = 6.727500e-02
max. abs. area error: 240.000000
Starting integration 45646
iter = 0, t = 0.000000e+00, delta_t = 1.000000e-02
iter = 10, t = 1.593742e-01, delta_t = 2.593742e-02
iter = 20, t = 5.727500e-01, delta_t = 6.727500e-02
```

Is there an issue with my files or is it just taking a lot of time ?
If I change the weights, can it goes more quickly ?

Thank you!

**Comment by mgastner** [comment]
Sorry about the slow response!

My hunch is that your problem is caused by areas with land area close to zero (e.g. Vatican city, Tuvalu). They are probably below the resolution of the default grid. You can try whether changing this line in cartogram.h:
`#define L (512)            /* Maximum dimension of the FFT lattice is L x L. */`
to
`#define L (1024)            /* Maximum dimension of the FFT lattice is L x L. */`
or even a larger power of 2 would help.
But realistically I think you must remove these countries (e.g. with https://mapshaper.org/). It's also not ideal that you set all target areas to the same value. Do you really want the Vatican to be as big as Italy?
We'll update the code soon to handle small areas more gracefully.

**Comment by jonadem** [comment]
I continued my investigations and at the end, I was able to get a result ! :-)

With the site you advised (https://mapshaper.org/), I simplified the world the most I could. I also removed Antarctica (I think it is important because it covers 2 corners of the map).
For the weights, I set the [population in 2018 found on worldmapper.org](https://worldmapper.org/wp-content/uploads/2018/04/People_TotalPopulation_2018.xlsx).

I modified `cartogram.h`:
`#define MAX_PERMITTED_AREA_ERROR (0.01)`
to
`#define MAX_PERMITTED_AREA_ERROR (3000)`
Indeed, my bounding box was huge (-28609897.500000 -29297244.000000 23573995.500000 22886649.000000).

Now that I have something working based on the maps of the world, I will try to map the GDP by country. If I get something showable, I let you know.

**Comment by mgastner** [comment]
Great to hear it worked for you. Certainly happy to see your results.

The MAX_PERMITTED_AREA_ERROR is the _relative_ permitted area difference that must be reached before the outer loop terminates. The scale of the bounding box doesn't influence this condition.
